### ISSUE TITLE
Error on "https://www.lesswrong.com"

### ISSUE THREAD

**Issue by markran** [PoziWorld/Scroll-To-Top-Button-extension#6] opened 2019-11-21 19:31 UTC
Hovering over any green link on the homepage of https://www.lesswrong.com causes Error: Permission denied to access property "offsetParent"

Only occurs with Scroll-To-Top-Button enabled.

Tested on Scroll-To-Top-Button 8.1 in Firefox 70.0.1 (x64) on Win10x64.

Before Hovering Green Link
<img width="978" alt="Before" src="https://user-images.githubusercontent.com/6378626/69370071-0b9e5980-0c52-11ea-8e87-34956ad148d6.png">

After Hovering Green Link
<img width="972" alt="After-Hovering-Over-Green-Link" src="https://user-images.githubusercontent.com/6378626/69370070-0b9e5980-0c52-11ea-837b-bd93f6825f67.PNG">

**Comment by PoziWorld** [comment] 2019-11-22 05:01
Thank you for your report!

Will look into it.

**Comment by PoziWorld** [comment] 2019-11-29 03:48
@markran,

Even though the issue can be “band-aided” (to add a rule that will make the extension work differently just on this site and not cause this issue) on the extension side, [reached out](https://github.com/LessWrong2/Lesswrong2/issues/2657) to their team to see if they can fix it on their side (on the website itself).

Or, would you prefer to have it fixed in Scroll To Top Button now? Don't know how much time it might take them or whether they would do it at all.

**Comment by jimrandomh** [comment] 2019-12-02 00:33
Some analysis of this issue on https://github.com/LessWrong2/Lesswrong2/issues/2657 . I'm not sure whether this is a bug in Firefox or a bug in Scroll To Top, but I'd be very surprised if LW was the only site affected.

**Comment by PoziWorld** [comment] 2019-12-02 01:39
> I'm not sure whether this is... a bug in Scroll To Top

This is not a bug in Scroll To Top Button.

The page nodes get removed by one of the website's scripts:
[See a debugging video](https://streamable.com/dnzw6)
_(you can skip 00:25-01:15, as it takes a lot of time for the browser to show the breakpoint stop in code because of the huge bundle)_

**Closed** 2019-12-02 05:45 UTC

**Comment by PoziWorld** [comment] 2019-12-02 05:53
@markran,

Thank you again for your report!

The issue has been band-aided, and the new version is now 8.1.1.

Your browser should automatically update the extension soon or you can force it to update via the “Check for Updates” option:

![“Check for Updates” to force the update](https://user-images.githubusercontent.com/5961162/69933803-d6c9a800-1484-11ea-960e-efab1f179f09.png)

**Comment by markran** [comment] 2019-12-05 22:28
Wow! Thanks for the prompt and thorough response. I can verify the issue is fixed in 8.1.1. Hopefully the LessWrong web team will address it on their end too.
